## Numpy Installation

In [ ]:
# Codeblock 1
! pip install numpy

In [1]:
# Codeblock 2
import numpy as np
np.__version__

'1.26.4'

## Array Initialization

In [2]:
# Codeblock 3
np.array([7,6,5,4,3,2])

### Alternative
# np.asarray([7,6,5,4,3,2])

array([7, 6, 5, 4, 3, 2])

In [3]:
# Codeblock 4
print(np.asarray([7,6,5,4,3,2]))

[7 6 5 4 3 2]


In [4]:
# Codeblock 5
[7,6,5,4,3,2]

### Returns the exact same result.
# print([7,6,5,4,3,2])

[7, 6, 5, 4, 3, 2]

In [5]:
# Codeblock 6
print(np.asarray([[7,6,5,4,3,2], 
                  [9,8,7,6,5,4]]), end='\n\n')

print([[7,6,5,4,3,2], 
       [9,8,7,6,5,4]])

[[7 6 5 4 3 2]
 [9 8 7 6 5 4]]

[[7, 6, 5, 4, 3, 2], [9, 8, 7, 6, 5, 4]]


In [6]:
# Codeblock 7
A = [2,4,6,8]
B = np.array(A)   # Convert to Numpy array.
C = B.tolist()    # Convert to Python list.

print(B)
print(C)

[2 4 6 8]
[2, 4, 6, 8]


In [7]:
# Codeblock 8
print('type(A):', type(A))
print('type(B):', type(B))
print('type(C):', type(C))

type(A): <class 'list'>
type(B): <class 'numpy.ndarray'>
type(C): <class 'list'>


In [10]:
# Codeblock 9
a=np.genfromtxt('data.txt', delimiter=',')
a

array([[  1.,   2., 666.],
       [  2.,   3., 988.]])

## Numpy Array Limitation

In [11]:
# Codeblock 10
D = [2, 'Hello', True, 9.886]
D

[2, 'Hello', True, 9.886]

In [12]:
# Codeblock 11
print(np.array(D))
print(np.array(D).tolist())

['2' 'Hello' 'True' '9.886']
['2', 'Hello', 'True', '9.886']


## Computational Speed an Memory Usage

In [13]:
# Codeblock 12
import time

E = [123] * 9999999
F = np.array(E, dtype='int8')

In [14]:
# Codeblock 13
def summation_python_sum(arr):
    start_time = time.time()
    sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time
    
def summation_numpy_sum(arr):
    start_time = time.time()
    np.sum(arr)
    end_time = time.time()

    total_time = end_time - start_time
    return total_time

In [15]:
# Codeblock 14
print('Python list with sum()\t\t: ', summation_python_sum(E), 'sec')
print('Python list with np.sum()\t: ', summation_numpy_sum(E), 'sec')
print('Numpy array with sum()\t\t: ', summation_python_sum(F), 'sec')
print('Numpy array with np.sum()\t: ', summation_numpy_sum(F), 'sec')

Python list with sum()		:  0.1337125301361084 sec
Python list with np.sum()	:  0.5769858360290527 sec
Numpy array with sum()		:  1.4658737182617188 sec
Numpy array with np.sum()	:  0.0075109004974365234 sec


### Memory Usage

In [16]:
# Codeblock 15
import sys

print('E (Python list):', sys.getsizeof(E), 'bytes')
print('F (Numpy array):', sys.getsizeof(F), 'bytes')

E (Python list): 80000048 bytes
F (Numpy array): 10000111 bytes


## Datatypes

In [17]:
# Codeblock 16
print(B)
print(B.dtype)
print(F.dtype)

[2 4 6 8]
int32
int8


In [19]:
# Codeblock 17
print(np.array([5, 5, 5, 5.3, 5]).dtype)
print(np.array([True, True, False]).dtype)

float64
bool


### The Integer and Float Datatypes

In [20]:
# Codeblock 18
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [21]:
# Codeblock 19
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---

## Indexing and Slicing

In [22]:
# Codeblock 20
G = np.array([9, 7, 5, 6, 4, 8, 2, 6, 9, 5, 2, 4, 1, 4])

In [23]:
# Codeblock 21
print('G[7]\t\t:', G[7])        #(1)
print('G[-2]\t\t:', G[-2])      #(2)
print('G[:3]\t\t:', G[:3])      #(3)
print('G[3:]\t\t:', G[3:])      #(4)
print('G[2:6]\t\t:', G[2:6])    #(5)
print('G[1:7:2]\t:', G[1:7:2])  #(6)
print('G[::3]\t\t:', G[::3])    #(7)

G[7]		: 6
G[-2]		: 1
G[:3]		: [9 7 5]
G[3:]		: [6 4 8 2 6 9 5 2 4 1 4]
G[2:6]		: [5 6 4 8]
G[1:7:2]	: [7 6 8]
G[::3]		: [9 6 2 5 1]


In [24]:
# Codeblock 22
H = np.array([6,4,5,7,4,3])
print('G[H]\t:', G[H])

G[H]	: [2 4 8 6 4 6]


### Multidimensional Arrays

In [25]:
# Codeblock 23
I = np.array([[3, 1, 5, 7], 
              [2, 5, 3, 2], 
              [3, 8, 5, 9],
              [4, 8, 2, 6]])
I

array([[3, 1, 5, 7],
       [2, 5, 3, 2],
       [3, 8, 5, 9],
       [4, 8, 2, 6]])

In [26]:
# Codeblock 24
I[0,2]

5

In [27]:
# Codeblock 25
I[:2,:3]

array([[3, 1, 5],
       [2, 5, 3]])

In [28]:
# Codeblock 26
I[:,1:3]

array([[1, 5],
       [5, 3],
       [8, 5],
       [8, 2]])

In [29]:
# Codeblock 27
I[:-1,1:3]

array([[1, 5],
       [5, 3],
       [8, 5]])

In [30]:
# Codeblock 28
I[[0,2], :3]

array([[3, 1, 5],
       [3, 8, 5]])

In [31]:
# Codeblock 29
I[[0,1,2], [0,1,2]]

array([3, 5, 5])

## Array Generation Functions

In [32]:
# Codeblock 30
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
# Codeblock 31
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# Codeblock 32
np.zeros((4,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [35]:
# Codeblock 33
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [36]:
# Codeblock 34
np.eye(N=6, M=4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
# Codeblock 35
np.diag([1,4,3,4,4])

array([[1, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

In [38]:
# Codeblock 36
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.33193418e-321],
       [1.78019082e-306, 1.37959740e-306, 2.29178686e-312]])

In [39]:
# Codeblock 37
J = np.full(shape=(3,5), fill_value=999)
J

array([[999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999]])

In [40]:
# Codeblock 38
np.full_like(J, fill_value=111)

array([[111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111]])

In [41]:
# Codeblock 39
print(np.empty_like(J), end='\n\n')
print(np.ones_like(J), end='\n\n')
print(np.zeros_like(J))

[[      0       0       0       0       0]
 [      0       0       0       0       0]
 [   1536       0       0 7602273       0]]

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Sequential Numbers

In [42]:
# Codeblock 40
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
# Codeblock 41
[i for i in range(20)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [44]:
# Codeblock 42
print(np.arange(3, 20, 2), end='\n\n')
print(np.arange(100, 0, -3), end='\n\n')
print(np.arange(20, 30, 0.5))

[ 3  5  7  9 11 13 15 17 19]

[100  97  94  91  88  85  82  79  76  73  70  67  64  61  58  55  52  49
  46  43  40  37  34  31  28  25  22  19  16  13  10   7   4   1]

[20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5
 27.  27.5 28.  28.5 29.  29.5]


In [45]:
# Codeblock 43
np.linspace(1, 15, 50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [ ]:
# Codeblock 44
np.geomspace(1, 15, 50)

## Random Numbers

In [46]:
# Codeblock 1
np.random.rand(10,3)

### Alternative
# np.random.random((10,3))

array([[0.20237701, 0.45050796, 0.92819633],
       [0.0311238 , 0.91292546, 0.90895532],
       [0.07317355, 0.27263394, 0.40486536],
       [0.49127385, 0.8321549 , 0.8428416 ],
       [0.76714252, 0.67377306, 0.213268  ],
       [0.99359111, 0.97184538, 0.62971937],
       [0.24358228, 0.64572177, 0.43588899],
       [0.48673836, 0.81785111, 0.60452054],
       [0.65022732, 0.07095168, 0.95544542],
       [0.14410054, 0.24482673, 0.08249012]])

In [47]:
# Codeblock 2
np.random.uniform(low=90, high=100, size=(5,5))

array([[97.91158656, 93.18955532, 95.68686127, 98.05408464, 92.17039237],
       [94.35039416, 97.17973531, 90.39095469, 91.06690321, 99.19238899],
       [93.12224396, 93.61360536, 99.28827431, 98.35343318, 99.81575142],
       [90.83245885, 91.75185566, 99.70239424, 94.06214556, 98.50447748],
       [95.77513768, 90.07760019, 97.0253463 , 91.6987261 , 92.32534217]])

In [48]:
# Codeblock 3
np.histogram(np.random.uniform(size=(50000)))

### Yields similar results
np.histogram(np.random.rand(50000))
# np.histogram(np.random.random(50000))

(array([4886, 5064, 5010, 4874, 4973, 5072, 5038, 4951, 5065, 5067],
       dtype=int64),
 array([2.15410234e-05, 1.00018146e-01, 2.00014751e-01, 3.00011357e-01,
        4.00007962e-01, 5.00004567e-01, 6.00001172e-01, 6.99997777e-01,
        7.99994383e-01, 8.99990988e-01, 9.99987593e-01]))

### Normal Distribution

In [49]:
# Codeblock 4
np.random.randn(6,4)

array([[-0.18037627, -0.3361307 , -0.2439686 , -0.14558759],
       [ 0.07207894, -0.72867758,  1.12033921, -0.23098253],
       [ 0.28819842, -1.06764023,  0.32172876, -0.31101436],
       [ 0.32663875,  0.80105638, -1.04975015,  0.24375155],
       [ 0.03368483,  1.67128271, -0.10726915, -0.26536589],
       [-0.38977945,  0.21767445,  1.3424627 , -0.08782592]])

In [50]:
# Codeblock 5
np.random.normal(loc=8, scale=3, size=(5,5))

array([[ 1.23228817,  5.75972134,  7.58692082,  4.41643617,  6.44278461],
       [ 4.95979402,  8.30153828,  7.33831479,  8.05370828,  9.3399523 ],
       [ 7.86557572,  0.06490603,  8.57783644,  8.82136299,  1.54457145],
       [10.52337975, 10.86448313,  9.03125541,  8.01437783, 10.14289864],
       [13.67196053,  4.00102507,  7.40154876,  7.4016695 , 14.94153762]])

In [51]:
# Codeblock 6
np.histogram(np.random.normal(loc=0, scale=1, size=50000))

### Yields similar result
np.histogram(np.random.randn(50000))

(array([   35,   458,  2546,  8316, 14516, 14147,  7478,  2128,   338,
           38], dtype=int64),
 array([-3.90020395, -3.11024227, -2.32028058, -1.53031889, -0.74035721,
         0.04960448,  0.83956616,  1.62952785,  2.41948954,  3.20945122,
         3.99941291]))

### Random Integer

In [52]:
# Codeblock 7
np.random.randint(low=5, high=10, size=(20,3))

array([[5, 9, 9],
       [7, 8, 5],
       [5, 5, 7],
       [8, 9, 6],
       [9, 5, 8],
       [5, 5, 9],
       [5, 9, 7],
       [5, 5, 8],
       [9, 7, 8],
       [6, 8, 7],
       [9, 7, 7],
       [8, 9, 8],
       [9, 7, 6],
       [5, 7, 5],
       [7, 6, 8],
       [6, 5, 5],
       [5, 7, 9],
       [5, 5, 9],
       [5, 6, 5],
       [8, 6, 9]])

### Array Shuffling

In [53]:
# Codeblock 8
K = np.random.randint(1, 30, size=10)
K

array([25, 27,  7, 12,  7, 10,  8, 23, 11, 25])

In [54]:
# Codeblock 9
print('K before shuffle\t: ', K)
np.random.shuffle(K)
print('K after shuffle\t\t: ', K)

K before shuffle	:  [25 27  7 12  7 10  8 23 11 25]
K after shuffle		:  [27 10 25 12 11  7  8  7 23 25]


### Random Choice

In [ ]:
# Codeblock 10
print(np.random.choice(K), end='\n\n')                #(1)
print(np.random.choice(K, size=(2,3)), end='\n\n')    #(2)
print(np.random.choice(K, size=(2,4), replace=False)) #(3)

### Seed

In [ ]:
# Codeblock 11
np.random.seed(99)
np.random.randint(low=0, high=10, size=(2,5))

In [ ]:
# Codeblock 12
np.random.seed(99)
np.random.randint(low=0, high=10, size=(2,5))

## View and Copy

### View

In [ ]:
# Codeblock 13
L = np.array([55, 66, 77, 88, 99])
M = L
print(M)

In [ ]:
# Codeblock 14
M[0] = 15
print('L:', L)
print('M:', M)

### Copy

In [ ]:
# Codeblock 15
L = np.array([55, 66, 77, 88, 99])
M = L.copy()
M[0] = 15

print('L:', L)
print('M:', M)

## Mathematical Functions

### Basic Mathematical Operations

In [ ]:
# Codeblock 16
N = np.array([1,2,3], dtype='int32')
O = np.array([4,5,6], dtype='int32')

In [ ]:
# Codeblock 17
print(N + O)
print(N - O)
print(N * O)
print(N / O)

In [ ]:
# Codeblock 18
print(np.add(N, O))
print(np.subtract(N, O))
print(np.multiply(N, O))
print(np.divide(N, O))

In [ ]:
# Codeblock 19
print(N + 5)
print(N - 5)
print(N * 5)
print(N / 5)

In [ ]:
# Codeblock 20
O = np.array([[2, 1, 0], 
              [5, 4, 3], 
              [8, 7, 6], 
              [1, 0, 9]])

P = np.array([[4, 3], 
              [6, 5], 
              [8, 7]])

np.matmul(O, P)

In [ ]:
# Codeblock 21
Q = np.array([-56, 92, -24, -66, 72, -75, 90, 0, 32, 51])

print(np.sign(Q))
print(np.negative(Q))
print(np.abs(Q))      # Alternative: np.absolute()

### GCD and LCM

In [ ]:
# Codeblock 22
print(np.gcd(81, 72))    #(1)
print(np.lcm([3, 6, 9], 24))    #(2)
print(np.lcm([3, 12, 9], [24, 16, 3]))    #(3)

### Exponential Functions

In [ ]:
# Codeblock 23
print(np.power(8, 3))
print(np.power([1,2,3,4], 2))
print(np.power(144, 1/2))

In [ ]:
# Codeblock 24
print(np.square(6))             # Equivalent with: np.power(6,2)
print(np.sqrt([144,16,9,4]))    # Equivalent with: np.power([144,16,9,4], 1/2)
print(np.cbrt([343,27]))        # Equivalent with: np.power([343,27], 1/3)
print(np.exp([2,3,4]))          # Equivalent with: np.power(np.e, [2,3,4])

### Angular Conversion and Trigonometric Functions

In [ ]:
# Codeblock 25
R = np.array([0, 90, 180, 270])    # Angles in degree
S = np.array([0, np.pi/2, np.pi, np.pi*3/2])    # Angles in radian

print(np.deg2rad(R))
print(np.rad2deg(S))

In [ ]:
# Codeblock 26
T = np.deg2rad([0, 45, 60])

print(np.sin(T))
print(np.cos(T))
print(np.tan(T))

### Logarithmic Functions

In [ ]:
# Codeblock 27
U = [1, 2, 10, np.e]

print(np.log(U))
print(np.log2(U))
print(np.log10(U))

### Statistical Functions

In [ ]:
# Codeblock 28
V = np.array([1, 5, 4, 6, 8, 5, 4, 3, 2, 4, 7, 9, 5, 4, 3, 2, 0, 7, 9])

print('sum\t:', np.sum(V))
print('mean\t:', np.mean(V))
print('median\t:', np.median(V))
print('var\t:', np.var(V))
print('stddev\t:', np.std(V))
print('q1\t:', np.quantile(V, 0.25))
print('q2\t:', np.quantile(V, 0.5))
print('q3\t:', np.quantile(V, 0.75))
print('min\t:', np.min(V))
print('max\t:', np.max(V))

In [ ]:
# Codeblock 29
print('argmin\t:', np.argmin(V))
print('argmax\t:', np.argmax(V))

### Linear Algebra

In [ ]:
# Codeblock 30
W = np.array([10, 20, 30, 40])
X = np.array([3, 4, 5, 6])

In [ ]:
# Codeblock 31
np.dot(W, X)

In [ ]:
# Codeblock 32
print(np.inner(W, X))
print(np.outer(W, X))

In [ ]:
# Codeblock 33
Y = np.array([[2, 1, 0],
              [0, 4, 5],
              [2, 6, 3]])

In [ ]:
# Codeblock 34
np.transpose(Y)

### Alternative
# Y.T

In [ ]:
# Codeblock 35
np.linalg.inv(Y)

In [ ]:
# Codeblock 36
np.linalg.det(Y)

In [ ]:
# Codeblock 37
eigenvalues, eigenvectors = np.linalg.eig(Y)

print(eigenvalues, end='\n\n')
print(eigenvectors)

## Logical and Bitwise Operators

### Logical Operators

In [ ]:
# Codeblock 38
Z = np.array([True, True, True])
AA = np.array([False, True, True])

In [ ]:
# Codeblock 39
print(np.logical_and(Z, AA))
print(np.logical_or(Z, AA))
print(np.logical_xor(Z, AA))

In [ ]:
# Codeblock 40
print('np.any(Z): ', np.any(Z))
print('np.all(Z): ', np.all(Z), end='\n\n')
print('np.any(AA):', np.any(AA))
print('np.all(AA):', np.all(AA))

In [ ]:
# Codeblock 41
AB = np.array([2, 0, 3, -5, 5, -1, 2, -4])

print(np.any(AB > 4))    #(1)
print(np.all(AB > 4))    #(2)

### Bitwise Operators

In [ ]:
# Codeblock 42
print(np.bitwise_and(12, 13))
print(np.bitwise_or(12, 13))
print(np.bitwise_xor(12, 13))

In [ ]:
# Codeblock 43
print(np.binary_repr(12))
print(np.binary_repr(13))

## Search and Sort

In [ ]:
# Codeblock 44
AC = np.array([9, 4, 5, 3, 2, 6, 8, 6, 5, 4, 5, 5, 3, 2])

mask = AC > 5  #(1)
mask

In [ ]:
# Codeblock 45
AC[mask]

In [ ]:
# Codeblock 46
AC[AC > 5]

In [ ]:
# Codeblock 47
AC[(AC > 5) & (AC != 9)]

In [ ]:
# Codeblock 48
AC[np.where((AC > 5) & (AC != 9))]

In [ ]:
# Codeblock 49
np.where((AC > 5) & (AC != 9))

# Recall the elements of AC: [9, 4, 5, 3, 2, 6, 8, 6, 5, 4, 5, 5, 3, 2].

In [ ]:
# Codeblock 50
print(AC)
print(np.where(AC > 5, 0, AC+2))

In [ ]:
# Codeblock 51
np.unique(AC, return_counts=True)

### Sorting

In [ ]:
# Codeblock 52
AD = np.array([77,33,44,99,22,88,55,11,66])
AE = np.array(["Elon Musk", "Bill Gates", "Joe Biden", "Barack Obama"])

print(np.sort(AD))
print(np.sort(AE))

In [ ]:
# Codeblock 53
print(np.flip(np.sort(AD)))
print(np.flip(np.sort(AE)))

### Alternative
# print(np.sort(AD)[::-1])
# print(np.sort(AE)[::-1])

In [ ]:
# Codeblock 54
np.argsort(AD)

# Recall the elements of AD: [77, 33, 44, 99, 22, 88, 55, 11, 66].

In [ ]:
# Codeblock 55
AD[np.argsort(AD)]

In [ ]:
# Codeblock 56
AF = np.array([[3, 1, 5, 7],
               [8, 9, 3, 2], 
               [4, 8, 2, 6]])

In [ ]:
# Codeblock 57
print(np.sort(AF, axis=0), end='\n\n')
print(np.sort(AF, axis=1))

In [ ]:
# Codeblock 58
AG = np.arange(13)
AG

In [ ]:
# Codeblock 59
print(np.roll(AG, shift=3))     #(1)
print(np.roll(AG, shift=-3))    #(2)

## Shape and Reshape

In [ ]:
# Codeblock 60
AH = np.array([[0,   1,  2,  3,  4,  5], 
               [6,   7,  8,  9, 10, 11], 
               [12, 13, 14, 15, 16, 17], 
               [18, 19, 20, 21, 22, 23], 
               [24, 25, 26, 27, 28, 29]])

len(AH)

In [ ]:
# Codeblock 61
AH.shape

In [ ]:
# Codeblock 62
AH.reshape(3,10)

In [ ]:
# Codeblock 63
AH.reshape(2,3,5)

In [ ]:
# Codeblock 64
AH.reshape(-1,5)

In [ ]:
# Codeblock 65
AH.reshape(-1,1)

In [ ]:
# Codeblock 66
AH.flatten()

### Alternative
# AH.reshape(-1)

In [ ]:
# Codeblock 67
AH.flatten()[:, np.newaxis]

### Alternative
# AH.flatten().reshape(-1,1)

In [ ]:
# Codeblock 68
AH.flatten()[np.newaxis, :]

### Alternative
# AH.flatten().reshape(1,-1)

## Concatenation and Splitting

In [ ]:
# Codeblock 69
AI = np.array(np.random.randint(0, 5, (2,4)))
AJ = np.array(np.random.randint(5, 10, (2,4)))

print(AI, end='\n\n')
print(AJ)

In [ ]:
# Codeblock 70
np.vstack((AI,AJ))

In [ ]:
# Codeblock 71
np.hstack((AI,AJ))

In [ ]:
# Codeblock 72
print(np.vstack((AI,AJ,AJ,AJ,AI)), end='\n\n')
print(np.hstack((AI,AJ,AJ,AJ,AI)))

In [ ]:
# Codeblock 73
print(np.append(AI, AJ), end='\n\n')
print(np.append(AI, AJ, axis=0), end='\n\n')
print(np.append(AI, AJ, axis=1))

In [ ]:
# Codeblock 74
print(np.concatenate([AI, AI, AI], axis=None), end='\n\n')
print(np.concatenate([AI, AI, AI]), end='\n\n')
print(np.concatenate([AI, AI, AI], axis=1))

### Splitting

In [ ]:
# Codeblock 75
AK = np.random.randint(0, 10, (20))
AK

In [2]:
# Codeblock 76
np.split(AK, indices_or_sections=[3,5])

NameError: name 'np' is not defined

In [ ]:
# Codeblock 77
AL = np.random.randint(0, 10, (5,6))
AL

In [ ]:
# Codeblock 78
np.vsplit(AL, [2,4])

### Alternative
# np.split(AL, [2,4], axis=0)

In [ ]:
# Codeblock 79
np.hsplit(AL, [3,4])

### Alternative
# np.split(AL, [3,4], axis=1) #equivalent